const actionTypes = {
  FETCH_FLAVORS: "FETCH_FLAVORS",
  FETCH_RECIPES: "FETCH_RECIPES",

  SET_LAST_COMMENT: "SET_LAST_COMMENT",
  DELETE_RECIPE: "DELETE_RECIPE",

  FETCH_TAGS: "FETCH_TAGS",
  CREATE_TAGS: "CREATE_TAGS",
  SET_CREATED_TAG: "SET_CREATED_TAG",
  SET_SEARCHED_TAG: "SET_SEARCHED_TAG",
  SET_SEARCHED_FLAVOR: "SET_SEARCHED_FLAVOR",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_ALL_USER: "SET_ALL_USER"
};

export default actionTypes;
